<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "viresponsiveimages"
 *
 * Auto generated by Extension Builder 2014-11-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Responsive Images for fluid-styled-content',
	'description' => 'Configurable backend and frontend implementation of the responsive image handling.',
	'category' => 'fe',
	'author' => 'Visol',
	'author_email' => 'info@visol.ch',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.9.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '9.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
